### ISSUE TITLE
生成的图片错误

### ISSUE THREAD

**Issue by fak111** [haibo-qiu/SynFace#10]
python -u data/DiscoFaceGAN/syn_images.py --num_id 1000\
                                          --samples_perid 10 \
                                          --save_path ./data/datasets/p1k-10/ \
                                          --model ./data/DiscoFaceGAN/pretrained/network-snapshot-020126.pkl
                                         我是用这行命令之后生成的图像是
                                         这样的
                                         
![image](https://github.com/haibo-qiu/SynFace/assets/97438502/4203bed9-a75f-4e64-8eeb-9f82b3b4d95e)

**Comment by fak111** [comment]
我反复检查了模型  发现大小没有问题。。奇怪的是之前使用还能生成人脸图片，现在重复检查了一个下午仍然还是错误 @haibo-qiu

**Comment by haibo-qiu** [comment]
Hi @fak111，

你如果之前用的时候都还能生成人脸的话，我觉得大概率可能是你的环境出问题了。

[DiscoFaceGAN](https://github.com/microsoft/DiscoFaceGAN)这个repo已经两年多没更新了，我自己的这个repo也差不多，所以我感觉不太可能是代码层面的问题（如果你没做其他修改的话）。你给出的这些示例，我之前也没遇到过。

可以去重点检查一些环境里面某些重要package的版本，尤其是一些涉及到读取/写入的，看看是否能对得上。如果这些都能对得上但依旧出问题，那十分抱歉我也没其他想法了。

**Comment by fak111** [comment]
@haibo-qiu  你是我的超人！  
 确实是环境问题
换到了另一台机器重新配置了下  就能生成正常图像！！
感谢大佬

**Comment by haibo-qiu** [comment]
👍解决了就好
