### ISSUE TITLE
Synthetic Generated Dataset

### ISSUE THREAD

**Issue by jinchao2001** [haibo-qiu/SynFace#11]
Hi, can you share the synthetically generated dataset which is used in experiments again? It seems the former link has expired.

**Comment by haibo-qiu** [comment]
Hi @jc1120200200,
You can refer to this google drive [link](https://drive.google.com/file/d/17bJwCYFQcm9_PoUshiYFKo5E9LYmMMDC/view).

**Comment by jinchao2001** [comment]
> Hi @jc1120200200, You can refer to this google drive [link](https://drive.google.com/file/d/17bJwCYFQcm9_PoUshiYFKo5E9LYmMMDC/view).

Thank you very much! Wishing you success in your work and happiness in life.
