### ISSUE TITLE
Could you share network-snapshot-020126.pkl?

### ISSUE THREAD

**Issue by Jiazhen1997** [haibo-qiu/SynFace#2]
Could you please share network-snapshot-020126.pkl? Thanks.

**Comment by haibo-qiu** [comment]
Hi,

This pre-trained model is provided by [DiscoFaceGAN](https://github.com/microsoft/DiscoFaceGAN), and you can fetch it according to the url of [this line](https://github.com/haibo-qiu/SynFace/blob/bbfb10acae792a2f3d2382dd66c51bc4474029b3/data/syn_images.py#L167)
