### ISSUE TITLE
where it falls short

### ISSUE THREAD

**Issue by lgc-china** [haibo-qiu/SynFace#3]
There is some problem with your script，data root he sometimes doesn't work.And you did not specify the version of the downloaded dataset，This wastes a lot of unnecessary time。

**Comment by haibo-qiu** [comment]
You can follow the instruction of [face.evoLVe](https://github.com/ZhaoJ9014/face.evoLVe#data-zoo) to download and unzip the clean version of CASIA-WebFace.
<img width="614" alt="image" src="https://user-images.githubusercontent.com/31210561/155669834-d9b3f019-e1aa-4914-8355-201682e18ebc.png">

As for the data root issue, it works when precisely following the instruction of [README](https://github.com/haibo-qiu/SynFace#data-preparation), so you may check it yourself or change it according to your specific dataset path.
