### ISSUE TITLE
Synthetic Image Dataset

### ISSUE THREAD

**Issue by ErolCitak** [haibo-qiu/SynFace#5]
Hi,

Would you prefer to share the synthetically generated dataset which is used in experiments?

**Comment by haibo-qiu** [comment]
Hi @ErolCitak,

Sure, you can refer to our generated training dataset in this [onedirve](https://unisydneyedu-my.sharepoint.com/:u:/g/personal/hqiu2518_uni_sydney_edu_au/EST71RzmSUNEoM34T3WEeh4BPbpRmvmbpKo-iaJ7w9ORlA?e=1WJiLB) link.

**Comment by ErolCitak** [comment]
Thank you @haibo-qiu

**Comment by chinmayjog13** [comment]
@haibo-qiu it seems the link has expired, can you share it again?

**Comment by haibo-qiu** [comment]
Hi @chinmayjog13,
Here is the new onedirve [link](https://unisydneyedu-my.sharepoint.com/:u:/g/personal/hqiu2518_uni_sydney_edu_au/EST71RzmSUNEoM34T3WEeh4BhVcw_HmrqcK-vOWX0dmxAg).
