### ISSUE TITLE
Question about the value of scale s

### ISSUE THREAD

**Issue by zivzone** [haibo-qiu/SynFace#6]
Hi, @haibo-qiu 
Thanks for this incredible work and also your code. I'm curious about why you set the scale s =30 in the arcface loss.  
Based on [arcface loss paper](https://arxiv.org/pdf/1801.07698.pdf), they set s = 64. Is there any specific reason for you to set s = 30?

BR,
Ziv

**Comment by haibo-qiu** [comment]
Hi @zivzone

Back to that time, there was no official pytorch implementation for arcface. 

So I mainly followed a popular third-party implementation [arcface-pytorch](https://github.com/ronghuaiyang/arcface-pytorch)  for experiments, which set s=30 as you can see [here](https://github.com/ronghuaiyang/arcface-pytorch/blob/47ace80b128042cd8d2efd408f55c5a3e156b032/train.py#L58). And I also did not explore the difference between 30 and 64.

Hope this might help you : )

Best,
Haibo

**Comment by zivzone** [comment]
Hi @haibo-qiu  ,
Got it! Thank you for your reply!

BR,
Ziv
