### ISSUE TITLE
compatibility SynFace and DiscoGAN

### ISSUE THREAD

**Issue by una-kelly** [haibo-qiu/SynFace#7]
Hi, I'm trying to use your repository, but I have issues in complying with both the requirements for SynFace and DiscoGAN. For example, the CUDA requirements for tensorflow=1.12 (required by DisoGAN) and for pytorch=1.8.1 (SynFace) conflict with each other. How did you work around these issues? Do you have any advice for how to work with both SynFace and DiscoGAN? Thanks.

**Comment by haibo-qiu** [comment]
Hi @una-kelly ,

The main requirements of DiscoGAN are listed as below:
![image](https://user-images.githubusercontent.com/31210561/200816553-f718c107-efc4-4809-b80a-89ca436591e6.png)

The running environment of SynFace uses cuda 10.2 and cudnn 7.6.5, which is supposed to work for DiscoGAN as long as you have the right TensorFlow installed.

Do you have any specific issues when you install these packages?

By the way, the version 1.8.1 restriction for PyTorch is not necessary as we do not use any uncommon operations. Version 1.5 1.6 ... 1.10 should all work. Also, from my own experience, version 1.13 TensorFlow also works for DiscoGAN.

**Comment by una-kelly** [comment]
Hi @haibo-qiu ,
thanks for you quick reply. I tried with Tensorflow 1.12 and 1.13, but I think the problem is that neither is compatible with cuda 10.2.

**Comment by haibo-qiu** [comment]
Hi @una-kelly,

My current conda environment is using TensorFlow 1.13, Pytorch 1.8.1, and Cuda 10.2.89. You can refer to this [environment yml file](https://gist.github.com/haibo-qiu/86c7c34650039bf04917a07238c62224).

So it looks like as least TensorFlow 1.13 can work with Cuda 10.2, you may get errors from something else.

In my opinion, a possible solution is that you first install TensorFlow with a compatible version of Cuda that can run on your machine. Then according to the Cuda version, find a suitable PyTorch to install. As I mentioned before, SynFace does not use any uncommon operations, so a regular version of PyTorch is supposed to work.

If the above approach still does not work, then you might need to build two separate environments for running.

**Comment by una-kelly** [comment]
Hi @haibo-qiu,

After googling I found that Tensorflow 1.12 and 1.13 wouldn't work with Cuda 10.2, so that's why I thought that was the problem. But you're right, TF 1.13 does work with Cuda 10.2, it just seems I was using the wrong Cudnn and when I used 7.6.5 like you suggested it worked. Thanks!

**Comment by haibo-qiu** [comment]
That's great!
