### ISSUE TITLE
Substantially improve performance

### ISSUE THREAD

**Issue by batchfly** [haibo-qiu/SynFace#9]
I'm questioning that does the method substantially improve the accuracy of face recognition.

If I understand your pipeline correctly,
the generative model was trained on WebFace which contains 500,000 samples. Then generate training images with the generative model. The recognition model is trained with synthetic images.

But **why not directly train the recognition model on WebFace**?

Does the whole pipeline substantially improve the accuracy?

**Comment by haibo-qiu** [comment]
Hi @batchfly,

This method does not aim to develop a new module or pipeline to significantly enhance face recognition accuracy. Instead, it focuses on addressing privacy concerns and examining the various effects of different facial attributes using synthetic data. For more information about our motivation, please refer to the **Introduction** section of our [paper](https://arxiv.org/pdf/2108.07960.pdf).

Furthermore, our paper utilizes the generative model from [DiscoFaceGAN](https://github.com/microsoft/DiscoFaceGAN), which has been trained on the FFHQ dataset.

**Comment by batchfly** [comment]
@haibo-qiu Thanks for the clarification. Now I kind of understand your point.

**Comment by haibo-qiu** [comment]
That's great! 

Feel free to reopen this issue if you have any further questions.
